# Generated by Django 2.1.7 on 2019-04-03 10:49

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('title', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('image_url', models.URLField(blank=True, max_length=400, null=True)),
                ('thumbnail', models.ImageField(default='homepage/img/no-image-icon.png', upload_to='Album/')),
                ('detail', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel_professor_en', models.CharField(blank=True, max_length=32, null=True)),
                ('tel_lab_en', models.CharField(blank=True, max_length=32, null=True)),
                ('tel_professor_ko', models.CharField(blank=True, max_length=32, null=True)),
                ('tel_lab_ko', models.CharField(blank=True, max_length=32, null=True)),
                ('address_en', models.CharField(blank=True, max_length=128, null=True)),
                ('address_professor_en', models.CharField(blank=True, max_length=64, null=True)),
                ('address_lab_en', models.CharField(blank=True, max_length=64, null=True)),
                ('address_ko', models.CharField(blank=True, max_length=128, null=True)),
                ('address_professor_ko', models.CharField(blank=True, max_length=64, null=True)),
                ('address_lab_ko', models.CharField(blank=True, max_length=64, null=True)),
                ('email_professor', models.EmailField(blank=True, max_length=32, null=True)),
                ('location', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('submitted', models.BooleanField(default=False)),
                ('year', models.IntegerField(choices=[(2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)], default=2019)),
                ('summary', models.CharField(max_length=144)),
                ('journal', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('detail', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='Main_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, max_length=400, null=True)),
                ('image', models.ImageField(default='homepage/img/no-image-icon.png', upload_to='main_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('position', models.CharField(choices=[('professor', 'professor'), ('member-MS', 'member-MS'), ('member-PHD', 'member-PHD'), ('member-INTERN', 'member-INTERN'), ('alumni-MS', 'alumni-MS'), ('alumni-PHD', 'alumni-PHD')], default='member-MS', max_length=16)),
                ('position_num', models.IntegerField(default=0)),
                ('name_en', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name_ko', models.CharField(max_length=32)),
                ('course', models.CharField(blank=True, max_length=64, null=True)),
                ('research', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.EmailField(max_length=32)),
                ('tel', models.CharField(blank=True, max_length=32, null=True)),
                ('office', models.CharField(blank=True, max_length=128, null=True)),
                ('affiliation', models.CharField(blank=True, max_length=64, null=True)),
                ('image_url', models.URLField(blank=True, max_length=400, null=True)),
                ('image', models.ImageField(default='homepage/img/no-image-icon.png', upload_to='member_images/')),
                ('detail', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('title', models.CharField(max_length=144, primary_key=True, serialize=False)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('institute', models.CharField(blank=True, max_length=64, null=True)),
                ('business', models.CharField(blank=True, max_length=64, null=True)),
                ('term_start', models.DateField(blank=True, null=True)),
                ('term_end', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('research_name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('research_detail', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchArea',
            fields=[
                ('research_area', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('seminar', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('lecturer', models.CharField(max_length=64)),
                ('institute', models.CharField(blank=True, max_length=64, null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='research',
            name='research_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.ResearchArea'),
        ),
    ]
