# Generated by Django 2.1.7 on 2019-04-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20190403_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
